### ISSUE TITLE
How to get next/previous posts titles?

### ISSUE THREAD

**Issue by ghost** [daveis/manifesto-anchor-theme#6]
I just try to use article_previous_title but it doesn't work.
Do you have any idea to do this?

**Comment by daveis** [comment]
**This is not a theme issue.** The function you are trying to call does not exist in Anchor. You must write that function yourself in the theme's functions.php file, and then call your new function at the place you want to use it in the theme.

@Jelenadria, I am going to assume you are using my Manifesto theme since you are posting this question here. I am also going to assume you want "Prev / Next" links at the bottom of an article to show you the title of the posts instead of just the "Prev / Next" words.

I have created the functions required to do this and I will post them in a gist for you shortly.

**Helpful note:** the available functions you can use are listed at http://anchorcms.com/docs. It is also helpful to simply look at the functions in the cms files themselves. It will help you see how they are constructed. Under your main anchor installation, look at anchor > functions > (pick any php file to review).

For example. Here is are the functions for an article:
https://github.com/anchorcms/anchor-cms/blob/master/anchor/functions/articles.php

**Comment by daveis** [comment]
@Jelenadria 
Here is what you need to make this work:
1. Copy the code from [this gist](https://gist.github.com/daveis/e87da993ef99fea58d6d)
2. Put those two functions at the bottom of the `functions.php` file inside the theme.
3. Copy the code from [this other gist](https://gist.github.com/daveis/4c949e9c5fa4ded044af)
4. Open article.php from my Manifesto theme. Scroll down the code which handles the pagination (Prev/Next) stuff. This should be lines 83 - 85. Delete the existing pagination stuff and paste in the new code you copied in the previous step.
5. Save everything and go test your site. Pagination when inside an article should now show the title of the previous and next post! 

**Note:** You will almost certainly need to modify the CSS to make the new pagination layout look more pleasing. The current CSS assumes the very short words of "Prev" and "Next" and therefore can fit them both on the same line with a pipe divider. This will likely not work very well when you have a long article titles in the same position. 

I hope this helped you solve your problem, and to understand Anchor CMS a little bit better. If you are building something cool with my theme, please share a link so I can look at your creation!
